# Generated by Django 4.2.16 on 2025-07-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="country",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CN", "中国"),
                    ("US", "美国"),
                    ("GB", "英国"),
                    ("JP", "日本"),
                    ("KR", "韩国"),
                    ("DE", "德国"),
                    ("FR", "法国"),
                    ("CA", "加拿大"),
                    ("AU", "澳大利亚"),
                    ("SG", "新加坡"),
                    ("other", "其他"),
                ],
                max_length=10,
                null=True,
                verbose_name="机构国家/地区",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="是否审核通过"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_edu_email",
            field=models.BooleanField(default=False, verbose_name="是否教育邮箱"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="organization_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("university", "高等院校"),
                    ("research_institute", "科研院所"),
                    ("government", "政府机构"),
                    ("enterprise", "企业单位"),
                    ("ngo", "非政府组织"),
                    ("hospital", "医疗机构"),
                    ("other", "其他机构"),
                ],
                max_length=50,
                null=True,
                verbose_name="机构类型",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="organization",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="机构名称"
            ),
        ),
    ]
