# Generated by Django 4.2.16 on 2025-07-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_auditlog_userverification_userprofile_admin_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userverification",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="是否已验证"),
        ),
        migrations.AddField(
            model_name="userverification",
            name="verification_code",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="重置密码验证码"
            ),
        ),
        migrations.AlterField(
            model_name="userverification",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="过期时间"),
        ),
    ]
